security:
    encoders:
        App\Entity\User:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            provider: app_user_provider

            form_login: 
                # The route name that the login form submits to
                login_path: login
                # When the user tries to access a protected page, they are redirect here
                check_path: login
                # Secure the login from against CSRF
                csrf_token_generator: security.csrf.token_manager
                # The page users are redirect to when there is no previous page stored in the
                # session (for instance when the users access directly to the login page).
                default_target_path: admin_main_page
                username_parameter: _email
            
            logout: 
                # The route name the user can go to in order to logout
                path: logout
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds 
                path: /
            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication
    
    access_control:
         - { path: ^/admin/su, roles: ROLE_ADMIN }
         - { path: ^/admin, roles: ROLE_USER }
    
   